on:
  push:
    branches:
      - master
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    run: echo "REPO_NAME=$(echo ${{ github.repository }} | sed 's#.*/##')" >> $GITHUB_ENV

  test2:
    runs-on: ubuntu-latest
    run: echo "ORG_NAME=${{ github.repository_owner }}" >> $GITHUB_ENV
    
